# Generated by Django 6.0.3 on 2026-03-30 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('api', 'Api')], max_length=20)),
                ('total_findings_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('reopened_count', models.IntegerField(default=0)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('ci_provider', models.CharField(blank=True, default='', max_length=50)),
                ('raw_report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='scan_proj_created_idx')],
            },
        ),
    ]
