# Generated by Django 6.0.3 on 2026-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='scanner_type',
            field=models.CharField(choices=[('semgrep', 'Semgrep'), ('sarif', 'SARIF'), ('generic', 'Generic')], default='semgrep', max_length=20),
        ),
    ]
