# Generated by Django 6.0.3 on 2026-04-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_multi_scanner_and_archival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='new_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='resolved_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='total_findings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
