# Generated by Django 6.0.3 on 2026-03-31 19:40

import core.fields
import projects.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_encrypt_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='api_key',
            field=core.fields.EncryptedTextField(default=projects.models.generate_api_key, max_length=255),
        ),
    ]
