# Generated by Django 6.0.3 on 2026-04-03 22:13

import core.fields
import projects.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sla_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='api_key',
            field=core.fields.EncryptedTextField(default=projects.models.generate_api_key),
        ),
        migrations.AlterField(
            model_name='project',
            name='old_api_key',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
