# Generated by Django 6.0.3 on 2026-03-30 15:09

import django.db.models.deletion
import integrations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('jira', 'Jira'), ('linear', 'Linear')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('jira_instance_url', models.URLField(blank=True, default='')),
                ('jira_project_key', models.CharField(blank=True, default='', max_length=50)),
                ('jira_api_token', models.CharField(blank=True, default='', max_length=500)),
                ('jira_user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('linear_api_key', models.CharField(blank=True, default='', max_length=500)),
                ('linear_team_id', models.CharField(blank=True, default='', max_length=100)),
                ('webhook_secret', models.CharField(default=integrations.models.generate_webhook_secret, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='projects.project')),
            ],
            options={
                'ordering': ['provider'],
                'unique_together': {('project', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='StatusMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_status', models.CharField(max_length=100)),
                ('internal_status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('ignored', 'Ignored')], max_length=20)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_mappings', to='integrations.integrationconfig')),
            ],
            options={
                'ordering': ['external_status'],
                'unique_together': {('integration', 'external_status')},
            },
        ),
    ]
