# Generated by Django 6.0.3 on 2026-04-03 22:13

import core.fields
import integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_encrypt_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='jira_api_token',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='linear_api_key',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='webhook_secret',
            field=models.CharField(db_index=True, default=integrations.models.generate_webhook_secret, max_length=64),
        ),
    ]
