# Generated by Django 6.0.3 on 2026-03-30 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('line_start', models.IntegerField()),
                ('line_end', models.IntegerField()),
                ('code_snippet', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('ignored', 'Ignored')], default='new', max_length=20)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('false_positive_reason', models.TextField(blank=True, default='')),
                ('jira_ticket_id', models.CharField(blank=True, default='', max_length=100)),
                ('jira_ticket_url', models.URLField(blank=True, default='')),
                ('linear_ticket_id', models.CharField(blank=True, default='', max_length=100)),
                ('linear_ticket_url', models.URLField(blank=True, default='')),
                ('severity_override', models.CharField(blank=True, default='', max_length=20)),
                ('pr_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_findings', to='scans.scan')),
                ('last_seen_scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_findings', to='scans.scan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='findings.finding')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semgrep_rule_id', models.CharField(max_length=500)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ignored', 'Ignored')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='findings.rule'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('project_create', 'Project Create'), ('project_delete', 'Project Delete'), ('scan_upload', 'Scan Upload'), ('scan_push', 'Scan Push'), ('finding_status_change', 'Finding Status Change'), ('finding_false_positive', 'Finding False Positive'), ('rule_status_change', 'Rule Status Change'), ('integration_change', 'Integration Change'), ('api_key_regenerate', 'Api Key Regenerate')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='findings_au_project_ed5b6a_idx'), models.Index(fields=['user', 'created_at'], name='findings_au_user_id_ed1e1b_idx'), models.Index(fields=['action'], name='findings_au_action_f7cb23_idx')],
            },
        ),
        migrations.CreateModel(
            name='FindingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('status_change', 'Status Change'), ('false_positive', 'False Positive'), ('ticket_created', 'Ticket Created')], default='status_change', max_length=20)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('jira_ticket_url', models.URLField(blank=True, default='')),
                ('linear_ticket_url', models.URLField(blank=True, default='')),
                ('pr_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='findings.finding')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scans.scan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['finding', '-created_at'], name='fh_finding_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['project', 'status'], name='rule_proj_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('project', 'semgrep_rule_id')},
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'status'], name='findings_fi_project_b0fe82_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'rule'], name='findings_fi_project_1255f5_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['jira_ticket_id'], name='findings_fi_jira_ti_39da8e_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['linear_ticket_id'], name='findings_fi_linear__6e54ee_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['is_false_positive'], name='findings_fi_is_fals_64e168_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'status', 'is_false_positive'], name='finding_proj_status_fp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together={('project', 'rule', 'file_path', 'line_start', 'line_end')},
        ),
    ]
