# Generated by Django 6.0.3 on 2026-03-31 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
        ('projects', '0001_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('logout', 'Logout'), ('project_create', 'Project Create'), ('project_delete', 'Project Delete'), ('scan_upload', 'Scan Upload'), ('scan_push', 'Scan Push'), ('finding_status_change', 'Finding Status Change'), ('finding_false_positive', 'Finding False Positive'), ('rule_status_change', 'Rule Status Change'), ('integration_change', 'Integration Change'), ('api_key_regenerate', 'Api Key Regenerate')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', '-created_at'], name='finding_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['rule', 'is_false_positive'], name='finding_rule_fp_idx'),
        ),
        migrations.AddIndex(
            model_name='findinghistory',
            index=models.Index(fields=['new_status', 'created_at'], name='fh_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['semgrep_rule_id'], name='rule_semgrep_id_idx'),
        ),
    ]
