# Generated by Django 6.0.3 on 2026-03-31 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0004_add_password_change_action'),
        ('projects', '0004_sla_tracking'),
        ('scans', '0002_multi_scanner_and_archival'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=20)),
                ('max_resolution_hours', models.PositiveIntegerField(help_text='Maximum hours allowed to resolve findings of this severity.')),
                ('notification_threshold_hours', models.PositiveIntegerField(blank=True, help_text='Hours before deadline to send a warning notification.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['severity'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finding',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'sla_breached', 'status'], name='finding_sla_breach_idx'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='slapolicy',
            unique_together={('project', 'severity')},
        ),
    ]
