# Generated by Django 6.0.3 on 2026-04-01 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_sla_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_delete', 'Project Delete'), ('scan_upload', 'Scan Upload'), ('scan_push', 'Scan Push'), ('finding_status_change', 'Finding Status Change'), ('finding_false_positive', 'Finding False Positive'), ('rule_status_change', 'Rule Status Change'), ('comment_created', 'Comment Created'), ('comment_deleted', 'Comment Deleted'), ('integration_change', 'Integration Change'), ('api_key_regenerate', 'Api Key Regenerate'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('password_change', 'Password Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='finding',
            name='false_positive_reason',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='findingcomment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='findinghistory',
            name='notes',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
