# Generated by Django 6.0.3 on 2026-04-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0006_audit_action_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findinghistory',
            name='change_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('false_positive', 'False Positive'), ('ticket_created', 'Ticket Created'), ('ticket_closed', 'Ticket Closed')], default='status_change', max_length=20),
        ),
    ]
