# Generated by Django 6.0.3 on 2026-04-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0007_ticket_closed_change_type'),
        ('projects', '0005_alter_project_api_key_alter_project_old_api_key'),
        ('scans', '0003_alter_scan_new_count_alter_scan_reopened_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_delete', 'Project Delete'), ('scan_upload', 'Scan Upload'), ('scan_push', 'Scan Push'), ('finding_status_change', 'Finding Status Change'), ('finding_severity_override', 'Finding Severity Override'), ('finding_false_positive', 'Finding False Positive'), ('rule_status_change', 'Rule Status Change'), ('comment_created', 'Comment Created'), ('comment_deleted', 'Comment Deleted'), ('integration_change', 'Integration Change'), ('api_key_regenerate', 'Api Key Regenerate'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('password_change', 'Password Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='finding',
            name='line_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finding',
            name='line_start',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='WARNING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('line_end__gte', models.F('line_start'))), name='finding_line_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='slapolicy',
            constraint=models.CheckConstraint(condition=models.Q(('notification_threshold_hours__isnull', True), ('notification_threshold_hours__lt', models.F('max_resolution_hours')), _connector='OR'), name='sla_notification_lt_deadline'),
        ),
    ]
